//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKismi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler//Veritabanındaki ögrenci tablosunun degiskenleri bu class icerisinde belirtilir
    {
        public int OgrenciId { get; set; }//public olarak ögrenci ıd tanımlanıyor public tanımlanmasının sebebi her class ve metoddan erişilebilmesi
        public string Ad { get; set; }//Aynı sekilde diğer tablo nitelikleri de tanımlanıyor
        public string Soyad { get; set; }
        public string Bolum { get; set; }
        public Nullable<int> GirisYili { get; set; }
    }
}
